const STORAGE_KEY='meuFinanceiro.v1';
const REUSABLE_CARD_PREFIX='↻|';
const OPENING_BALANCE_MARKER='#OPENING_BALANCE';
const ZERO_BALANCE_MARKER='#OPENING_BALANCE_ZERO';
const PAYDAY_PREFIX='#SALARY|';
const categories={salary:{label:'Salário',icon:'↓'},home:{label:'Moradia',icon:'⌂'},food:{label:'Alimentação',icon:'◇'},transport:{label:'Transporte',icon:'↗'},health:{label:'Saúde',icon:'✚'},leisure:{label:'Lazer',icon:'✳'},other:{label:'Outros',icon:'·'}};
const money=value=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(value||0);
const isPicPay=name=>/pic\s*pay/i.test(name);
const dateLabel=value=>new Intl.DateTimeFormat('pt-BR',{day:'2-digit',month:'short'}).format(new Date(`${value}T12:00:00`)).replace('.','');
const todayISO=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
const monthKey=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`;
const emptyState=()=>({transactions:[],bills:[],plan:{salary:0,percent:10,saved:0},name:''});
let state=emptyState(),visibleMonth=new Date(new Date().getFullYear(),new Date().getMonth(),1),hidden=false,client=null,currentUser=null,savingBill=false,savingCardUse=false,savingBillPayment=false,savingOpening=false,savingPayday=false,editingBillId=null,selectedReusableBill=null;
const $=selector=>document.querySelector(selector);
function setupMessage(message){$('#authScreen').hidden=false;$('#authMessage').textContent=message;$('.app-shell').hidden=true}
function toast(msg){const el=$('#toast');el.textContent=msg;el.classList.add('visible');setTimeout(()=>el.classList.remove('visible'),2600)}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function fmt(value){return hidden?'••••••':money(value)}
function billPaymentMarker(id,month=visibleMonth){return `#PG|${id}|${monthKey(month)}`}
function billPayment(billId,month=visibleMonth){return state.transactions.find(t=>t.type==='expense'&&t.description===billPaymentMarker(billId,month))||null}
function isOpeningBalance(t){return t.description===OPENING_BALANCE_MARKER||t.description===ZERO_BALANCE_MARKER}
function openingBalance(){const rows=state.transactions.filter(isOpeningBalance).sort((a,b)=>(a.createdAt||'').localeCompare(b.createdAt||''));return rows[rows.length-1]||null}
function actualBalance(){const opening=openingBalance();if(!opening)return null;return state.transactions.filter(t=>!isOpeningBalance(t)&&t.date>=opening.date).reduce((sum,t)=>sum+(t.type==='income'?t.amount:-t.amount),opening.description===ZERO_BALANCE_MARKER?0:opening.amount)}
function paydayMarker(date){return `${PAYDAY_PREFIX}${date}`}
function paydayReceipt(date){return state.transactions.find(t=>t.type==='income'&&t.description===paydayMarker(date))||null}
function billOffset(b,month=visibleMonth){const due=new Date(`${b.dueDate}T12:00:00`);return(month.getFullYear()-due.getFullYear())*12+month.getMonth()-due.getMonth()}
function billActive(b,month=visibleMonth){const offset=billOffset(b,month);return offset>=0&&(b.remaining>=600||offset<b.remaining)}
function billDateInMonth(b,month=visibleMonth){const original=new Date(`${b.dueDate}T12:00:00`),day=Math.min(original.getDate(),new Date(month.getFullYear(),month.getMonth()+1,0).getDate());return `${month.getFullYear()}-${String(month.getMonth()+1).padStart(2,'0')}-${String(day).padStart(2,'0')}`}
function setView(hash=window.location.hash){const id=hash.slice(1),known=['inicio','lancamentos','faturas','planejamento'],view=known.includes(id)?id:'inicio',labels={inicio:'Visão geral',lancamentos:'Lançamentos',faturas:'Faturas',planejamento:'Planejamento'};$('#inicio').dataset.view=view;$('#pageTitle').textContent=labels[view];document.querySelectorAll('.nav-link').forEach(link=>link.classList.toggle('active',link.hash===`#${view}`));renderBills();renderTransactions(state.transactions.filter(t=>t.date.slice(0,7)===monthKey(visibleMonth)))}
function monthlyBills(month=visibleMonth){return state.bills.filter(b=>billActive(b,month)&&!billPayment(b.id,month))}
function billStats(month=visibleMonth){const scheduled=state.bills.filter(b=>billActive(b,month)),paid=scheduled.map(b=>({bill:b,payment:billPayment(b.id,month)})).filter(row=>row.payment),pending=scheduled.filter(b=>!billPayment(b.id,month));return{count:scheduled.length,paidCount:paid.length,paidAmount:paid.reduce((sum,row)=>sum+row.payment.amount,0),pendingCount:pending.length,pendingAmount:pending.reduce((sum,b)=>sum+b.amount,0)}}
function renderPaydays(){const list=$('#paydayList'),amount=(state.plan.salary||0)/2,hasOpening=Boolean(openingBalance());list.innerHTML='';$('#paydayMonth').textContent=new Intl.DateTimeFormat('pt-BR',{month:'long',year:'numeric'}).format(visibleMonth);for(const day of [5,20]){const date=`${monthKey(visibleMonth)}-${String(day).padStart(2,'0')}`,receipt=paydayReceipt(date),row=document.createElement('div');row.className='payday-row';const info=document.createElement('div');info.className='payday-info';const name=document.createElement('strong');name.textContent=`Dia ${day}`;const detail=document.createElement('span');detail.textContent=receipt?'Recebido':!hasOpening?'Defina seu saldo real primeiro':amount?`Previsto · ${money(amount)}`:'Defina seu salário no planejamento';info.append(name,detail);const button=document.createElement('button');button.className=receipt?'outline-button payday-received':'primary-button';button.textContent=receipt?'Recebido ✓':'Recebi';button.disabled=(!receipt&&(!hasOpening||!amount||date>todayISO()));button.addEventListener('click',()=>togglePayday(date,receipt,button));row.append(info,button);list.appendChild(row)}}
function setSignedIn(user){currentUser=user;$('#authScreen').hidden=true;$('.app-shell').hidden=false;$('#accountEmail').textContent=user.email||'Conta Google';const metadata=user.user_metadata||{};state.name=metadata.preferred_name||metadata.full_name||metadata.name||user.email?.split('@')[0]||'você';loadCloudData()}
async function loadCloudData(){try{
 const [transactions,bills,plan]=await Promise.all([
  client.from('transactions').select('*').order('date',{ascending:false}),
  client.from('bills').select('*').order('due_date',{ascending:true}),
  client.from('savings_plans').select('*').maybeSingle()
 ]);
 for(const result of [transactions,bills,plan])if(result.error)throw result.error;
 state.transactions=(transactions.data||[]).map(t=>({id:t.id,description:t.description,amount:Number(t.amount),type:t.type,category:t.category,date:t.date,createdAt:t.created_at}));
 state.bills=(bills.data||[]).map(b=>{const reusableCard=String(b.icon||'').startsWith(REUSABLE_CARD_PREFIX);return{id:b.id,name:b.name,amount:Number(b.amount),dueDate:b.due_date,remaining:b.remaining,icon:reusableCard?b.icon.slice(REUSABLE_CARD_PREFIX.length):b.icon,reusableCard}});
 if(plan.data)state.plan={salary:Number(plan.data.salary),percent:plan.data.percent,saved:Number(plan.data.saved)};else state.plan={salary:0,percent:10,saved:0};
 if(!state.transactions.length&&!state.bills.length&&!plan.data&&await offerLegacyImport())return loadCloudData();
 render();
 }catch(error){console.error(error);toast('Não foi possível carregar seus dados. Confira a configuração do banco.')}
}
async function offerLegacyImport(){
 let old;try{old=JSON.parse(localStorage.getItem(STORAGE_KEY)||'null')}catch{return false}
 if(!old||(!old.transactions?.length&&!old.bills?.length&&!old.plan?.salary&&!old.plan?.saved))return false;
 const marker=`meuFinanceiro.imported.${currentUser.id}`;if(localStorage.getItem(marker))return false;
 localStorage.setItem(marker,'offered');
 const count=(old.transactions?.length||0)+(old.bills?.length||0)+(old.plan?.salary||old.plan?.saved?1:0);
 if(!window.confirm(`Encontrei dados antigos salvos neste navegador (${old.transactions?.length||0} lançamentos, ${old.bills?.length||0} faturas${old.plan?.salary||old.plan?.saved?' e sua meta':''}). Quer importar uma cópia para a conta Google ${currentUser.email||'conectada'}? Nada será apagado deste dispositivo.`))return false;
 try{
  const transactions=(old.transactions||[]).map(({id,...t})=>({...t,user_id:currentUser.id}));
  const bills=(old.bills||[]).map(({id,dueDate,...b})=>({...b,due_date:dueDate,user_id:currentUser.id}));
  if(transactions.length){const result=await client.from('transactions').insert(transactions);if(result.error)throw result.error}
  if(bills.length){const result=await client.from('bills').insert(bills);if(result.error)throw result.error}
  if(old.plan?.salary||old.plan?.saved||old.plan?.percent){const result=await client.from('savings_plans').upsert({user_id:currentUser.id,salary:Number(old.plan.salary)||0,percent:Number(old.plan.percent)||0,saved:Number(old.plan.saved)||0},{onConflict:'user_id'});if(result.error)throw result.error}
  localStorage.setItem(marker,'done');toast(`${count} itens importados. A cópia antiga continua neste dispositivo.`);return true;
 }catch(error){localStorage.removeItem(marker);console.error(error);toast('A importação não foi concluída. Seus dados antigos continuam neste dispositivo.');return false}
}
async function persist(operation){try{const result=await operation();if(result?.error)throw result.error;await loadCloudData();return true}catch(error){console.error(error);toast('Não foi possível salvar. Seus dados continuam seguros; tente novamente.');return false}}
function render(){
 const month=monthKey(visibleMonth),items=state.transactions.filter(t=>t.date.slice(0,7)===month),salary=state.plan.salary||0,otherIncome=items.filter(t=>t.type==='income'&&!isOpeningBalance(t)&&(!salary||t.category!=='salary')).reduce((n,t)=>n+t.amount,0),income=salary+otherIncome,otherExpenses=items.filter(t=>t.type==='expense').reduce((n,t)=>n+t.amount,0),accountTotal=monthlyBills().reduce((n,b)=>n+b.amount,0),expenses=otherExpenses+accountTotal,balance=income-expenses;
 $('#today').textContent=new Intl.DateTimeFormat('pt-BR',{weekday:'short',day:'numeric',month:'short',year:'numeric'}).format(new Date());$('#monthLabel').textContent=new Intl.DateTimeFormat('pt-BR',{month:'long',year:'numeric'}).format(visibleMonth);
 $('#balance').textContent=fmt(balance);$('#incomeTotal').textContent=fmt(income);$('#expenseTotal').textContent=fmt(expenses);const real=actualBalance(),opening=openingBalance(),bills=billStats();$('#currentBalance').textContent=real===null?'—':fmt(real);$('#setOpeningBalance').textContent=opening?'Ajustar saldo real':'Definir saldo atual';$('#paidBillsMetric').textContent=`${bills.paidCount} de ${bills.count}`;$('#paidBillsCaption').textContent=`${fmt(bills.paidAmount)} pagos`;$('#pendingBillsMetric').textContent=fmt(bills.pendingAmount);$('#pendingBillsCaption').textContent=`${bills.pendingCount} ${bills.pendingCount===1?'conta pendente':'contas pendentes'}`;$('#monthlyNote').textContent=income||expenses?(balance>=0?'Dentro do planejado':'Contas acima da renda'):'Defina seu salário';
 $('#greetingName').textContent=state.name||'você';$('.avatar').textContent=(state.name||'M').charAt(0).toUpperCase();$('.mobile-profile').textContent=(state.name||'M').charAt(0).toUpperCase();
 const target=(state.plan.salary||0)*(state.plan.percent||0)/100,progress=target?Math.min(100,Math.round((state.plan.saved||0)/target*100)):0;
 $('#goalValue').textContent=fmt(target);$('#goalDetail').textContent=state.plan.salary?`${state.plan.percent}% do seu salário de ${fmt(state.plan.salary)}`:'Defina seu salário e sua meta mensal';$('#savedLabel').textContent=`${fmt(state.plan.saved||0)} guardados`;$('#progressPercent').textContent=`${progress}%`;$('#donutPercent').textContent=`${progress}%`;$('#savingsProgress').style.width=`${progress}%`;$('#savingsDonut').style.background=`conic-gradient(#8bce9a ${progress}%,#eef2ee ${progress}% 100%)`;
 $('#suggestion').lastElementChild.textContent=target?(progress>=100?'Meta do mês alcançada. Que conquista!':`Faltam ${fmt(Math.max(0,target-(state.plan.saved||0)))} para a meta deste mês.`):'Um pequeno passo por mês faz diferença.';
 renderBills();renderBillAlerts();renderPaydays();renderTransactions(items);$('#privacyButton').textContent=hidden?'⊘':'◉';
}
function renderBillAlerts(){const box=$('#billAlerts'),list=$('#billAlertsList');if(monthKey(visibleMonth)!==monthKey(new Date())){box.hidden=true;return}const today=new Date();today.setHours(0,0,0,0);const due=state.bills.filter(b=>billActive(b)&&!billPayment(b.id)).map(b=>({bill:b,date:new Date(`${billDateInMonth(b)}T00:00:00`)})).map(item=>({...item,days:Math.round((item.date-today)/86400000)})).filter(item=>item.days<=7).sort((a,b)=>a.days-b.days);list.innerHTML='';box.hidden=!due.length;if(!due.length)return;const overdue=due.filter(item=>item.days<0);$('#billAlertsTitle').textContent=overdue.length?`${overdue.length} conta${overdue.length===1?'':'s'} vencida${overdue.length===1?'':'s'} — marque como paga quando quitar`:'Contas para pagar nos próximos 7 dias';for(const item of due.slice(0,4)){const li=document.createElement('li'),when=item.days<0?`atrasada desde ${dateLabel(billDateInMonth(item.bill))}`:item.days===0?'vence hoje':`vence em ${item.days} dia${item.days===1?'':'s'}`;li.textContent=`${item.bill.name} · ${fmt(item.bill.amount)} · ${when}`;list.appendChild(li)}}
function renderBills(){const list=$('#billList'),empty=$('#emptyBills'),all=[...state.bills].sort((a,b)=>a.dueDate.localeCompare(b.dueDate)),period=all.filter(b=>billActive(b)||billPayment(b.id)),bills=$('#inicio').dataset.view==='faturas'?period:period.slice(0,3),committed=monthlyBills().reduce((n,b)=>n+b.amount,0);list.innerHTML='';empty.classList.toggle('visible',!period.length);list.hidden=!period.length;for(const b of bills){const row=document.createElement('div');row.className='bill-item';const recurring=b.remaining>=600,canReuse=isPicPay(b.name)||b.reusableCard,payment=billPayment(b.id),dueDay=billDateInMonth(b),paid=Boolean(payment);row.innerHTML=`<span class="bill-icon">${esc(b.icon)}</span><span class="bill-info"><strong>${esc(b.name)}${paid?'<span class="bill-paid">Paga</span>':''}</strong><span>Vence ${dateLabel(dueDay)} · ${recurring?'Conta recorrente':`${Math.max(1,b.remaining-Math.max(0,billOffset(b)))} ${b.remaining===1?'parcela':'parcelas'} restantes`}</span><span class="bill-tools"><button class="bill-action bill-edit">Editar</button><button class="bill-action bill-payment-toggle">${paid?'Desfazer pagamento':'Marcar como paga'}</button>${canReuse?`<button class="bill-action bill-reuse-toggle">${b.reusableCard?'Desmarcar limite reutilizável':'Marcar PicPay: limite reutilizável'}</button>${b.reusableCard?'<button class="bill-action bill-use">＋ Registrar uso</button>':''}`:''}</span></span><span class="bill-amount"><strong class="sensitive">${fmt(b.amount)}<small>/mês</small></strong><span class="sensitive">${paid?'Pagamento registrado':recurring?'Mensal, sem prazo':`Faltam ${fmt(b.amount*Math.max(1,b.remaining-Math.max(0,billOffset(b))))} no total`}</span></span><button class="bill-delete" aria-label="Remover conta" title="Remover conta">×</button>`;row.querySelector('.bill-edit').addEventListener('click',()=>editBill(b));const paidButton=row.querySelector('.bill-payment-toggle');paidButton.addEventListener('click',()=>toggleBillPaid(b,payment,paidButton));row.querySelector('.bill-reuse-toggle')?.addEventListener('click',()=>{const icon=`${b.reusableCard?'':REUSABLE_CARD_PREFIX}${b.icon}`;persist(()=>client.from('bills').update({icon}).eq('id',b.id)).then(ok=>ok&&toast(b.reusableCard?'Marcação removida.':'PicPay marcado para registrar o limite reutilizado.'))});row.querySelector('.bill-use')?.addEventListener('click',()=>{selectedReusableBill=b;$('#cardUseForm').reset();$('#cardUseForm').elements.date.value=todayISO();$('#cardUseTitle').textContent=`Registrar uso — ${b.name}`;openDialog('cardUseDialog')});row.querySelector('.bill-delete').addEventListener('click',()=>persist(()=>client.from('bills').delete().eq('id',b.id)).then(ok=>ok&&toast('Conta removida.')));list.appendChild(row)}$('#billsFooterText').textContent=period.length?`${fmt(committed)} previstos em contas neste mês`:'Suas contas organizadas, sem surpresas.'}
function renderTransactions(items){const filter=$('#categoryFilter').value,rows=$('#transactionRows'),empty=$('#emptyTransactions');rows.innerHTML='';const filtered=items.filter(t=>filter==='all'||t.category===filter).sort((a,b)=>b.date.localeCompare(a.date)),shown=$('#inicio').dataset.view==='lancamentos'?filtered:filtered.slice(0,8);empty.hidden=shown.length>0;for(const t of shown){const payment=/^#PG\|([^|]+)\|\d{4}-\d{2}$/.exec(t.description),payday=t.description.startsWith(PAYDAY_PREFIX),opening=isOpeningBalance(t),bill=payment?state.bills.find(b=>b.id===payment[1]):null,description=payment?`Fatura paga · ${bill?.name||'Conta'}`:payday?`Salário recebido · dia ${Number(t.description.slice(PAYDAY_PREFIX.length).slice(-2))}`:opening?'Saldo inicial':t.description,cat=payment?{label:'Fatura',icon:'✓'}:opening?{label:'Saldo inicial',icon:'◉'}:categories[t.category]||categories.other,tr=document.createElement('tr');tr.innerHTML=`<td>${esc(description)}</td><td><span class="category-cell"><span class="category-badge">${cat.icon}</span>${cat.label}</span></td><td>${dateLabel(t.date)}</td><td class="sensitive ${t.type==='income'?'value-income':'value-expense'}">${t.type==='income'?'+':'−'} ${fmt(opening&&t.description===ZERO_BALANCE_MARKER?0:t.amount)}</td><td><button class="row-delete" aria-label="Remover lançamento" title="Remover">×</button></td>`;tr.querySelector('.row-delete').addEventListener('click',()=>persist(()=>client.from('transactions').delete().eq('id',t.id)).then(ok=>ok&&toast('Lançamento removido.')));rows.appendChild(tr)}}
function editBill(b){editingBillId=b.id;const form=$('#billForm');form.reset();form.elements.name.value=b.name;form.elements.amount.value=b.amount;form.elements.dueDate.value=b.dueDate;form.elements.remaining.value=b.remaining>=600?600:b.remaining;form.elements.remaining.disabled=b.remaining>=600;form.elements.recurring.checked=b.remaining>=600;form.elements.icon.value=b.icon;form.elements.reusableCard.checked=b.reusableCard;$('#billDialogTitle').textContent='Editar conta';$('#billSubmitButton').textContent='Salvar alterações';openDialog('billDialog')}
async function toggleBillPaid(b,payment,button){if(savingBillPayment)return;savingBillPayment=true;button.disabled=true;const marker=billPaymentMarker(b.id),date=todayISO();try{const result=payment?await client.from('transactions').delete().eq('id',payment.id):await client.from('transactions').insert({user_id:currentUser.id,description:marker,amount:b.amount,type:'expense',category:'other',date});if(result.error)throw result.error;await loadCloudData();toast(payment?'Pagamento desfeito.':'Conta marcada como paga.')}catch(error){console.error(error);toast('Não foi possível atualizar o pagamento.')}finally{savingBillPayment=false;button.disabled=false}}
async function togglePayday(date,receipt,button){if(savingPayday)return;savingPayday=true;button.disabled=true;try{const result=receipt?await client.from('transactions').delete().eq('id',receipt.id):await client.from('transactions').insert({user_id:currentUser.id,description:paydayMarker(date),amount:(state.plan.salary||0)/2,type:'income',category:'salary',date:todayISO()});if(result.error)throw result.error;await loadCloudData();toast(receipt?'Recebimento desfeito.':'Salário recebido adicionado ao saldo real.')}catch(error){console.error(error);toast('Não foi possível atualizar o recebimento.')}finally{savingPayday=false;button.disabled=false}}
function showOpeningBalance(){const form=$('#openingBalanceForm'),opening=openingBalance();form.reset();form.elements.amount.value=opening?(opening.description===ZERO_BALANCE_MARKER?0:opening.amount):'';form.elements.date.value=opening?.date||todayISO();openDialog('openingBalanceDialog')}
function openDialog(id){$(`#${id}`).showModal()}
function bindForms(){
 $('#googleLogin').onclick=async()=>{const {error}=await client.auth.signInWithOAuth({provider:'google',options:{redirectTo:window.location.origin+window.location.pathname}});if(error)$('#authMessage').textContent=error.message};
 $('#signOut').onclick=async()=>{await client.auth.signOut();state=emptyState();$('#authScreen').hidden=false;$('.app-shell').hidden=true};
 $('#addTransaction').onclick=()=>{$('#transactionForm').reset();$('[name="date"]').value=todayISO();openDialog('transactionDialog')};$('#emptyAddTransaction').onclick=()=>$('#addTransaction').click();
 $('#transactionForm').addEventListener('submit',async e=>{e.preventDefault();const f=new FormData(e.currentTarget);const item={user_id:currentUser.id,description:f.get('description').trim(),amount:Number(f.get('amount')),type:f.get('type'),category:f.get('category'),date:f.get('date')};if(await persist(()=>client.from('transactions').insert(item))){e.currentTarget.closest('dialog').close();toast('Lançamento salvo.')}});
 const recurringToggle=$('#billForm').elements.recurring,remainingInput=$('#billForm').elements.remaining,reusableCardToggle=$('#billForm').elements.reusableCard;
 $('#addBill').onclick=()=>{editingBillId=null;$('#billForm').reset();$('#billDialogTitle').textContent='Adicionar conta';$('#billSubmitButton').textContent='Salvar conta';recurringToggle.checked=false;remainingInput.disabled=false;$('[name="dueDate"]').value=todayISO();openDialog('billDialog')};$('#emptyAddBill').onclick=()=>$('#addBill').click();
 recurringToggle.addEventListener('change',()=>{remainingInput.disabled=recurringToggle.checked;if(recurringToggle.checked)remainingInput.value=600;else if(Number(remainingInput.value)===600)remainingInput.value=''});
 $('#billForm').addEventListener('submit',async e=>{e.preventDefault();if(savingBill)return;const form=e.currentTarget,f=new FormData(form),name=f.get('name').trim();if(reusableCardToggle.checked&&!isPicPay(name)){toast('Marque essa opção somente na conta PicPay.');return}savingBill=true;const saveButton=form.querySelector('button.primary-button'),originalLabel=saveButton.textContent;saveButton.disabled=true;saveButton.textContent='Salvando…';const bill={user_id:currentUser.id,name,amount:Number(f.get('amount')),due_date:f.get('dueDate'),remaining:recurringToggle.checked?600:Number(f.get('remaining')),icon:`${reusableCardToggle.checked?REUSABLE_CARD_PREFIX:''}${f.get('icon')}`};try{const result=editingBillId?await persist(()=>client.from('bills').update(bill).eq('id',editingBillId)):await persist(()=>client.from('bills').insert(bill));if(result){form.closest('dialog').close();toast(editingBillId?'Conta atualizada.':'Conta adicionada ao cálculo mensal.');editingBillId=null}}finally{savingBill=false;saveButton.disabled=false;saveButton.textContent=originalLabel}});
 $('#cardUseForm').addEventListener('submit',async e=>{e.preventDefault();if(savingCardUse||!selectedReusableBill)return;savingCardUse=true;const form=e.currentTarget,button=form.querySelector('button.primary-button'),label=button.textContent;button.disabled=true;button.textContent='Salvando…';const f=new FormData(form),detail=f.get('description').trim()||'compra',item={user_id:currentUser.id,description:`Uso ${selectedReusableBill.name}: ${detail}`.slice(0,60),amount:Number(f.get('amount')),type:'expense',category:'other',date:f.get('date')};try{if(await persist(()=>client.from('transactions').insert(item))){form.closest('dialog').close();toast('Uso do cartão entrou no saldo previsto.')}}finally{savingCardUse=false;button.disabled=false;button.textContent=label;selectedReusableBill=null}});
 $('#setOpeningBalance').onclick=showOpeningBalance;
 $('#openingBalanceForm').addEventListener('submit',async e=>{e.preventDefault();if(savingOpening)return;savingOpening=true;const form=e.currentTarget,button=form.querySelector('button.primary-button'),f=new FormData(form),amount=Number(f.get('amount')),opening=openingBalance(),item={user_id:currentUser.id,description:amount===0?ZERO_BALANCE_MARKER:OPENING_BALANCE_MARKER,amount:amount===0?0.01:amount,type:'income',category:'other',date:f.get('date')};button.disabled=true;try{const ok=opening?await persist(()=>client.from('transactions').update(item).eq('id',opening.id)):await persist(()=>client.from('transactions').insert(item));if(ok){form.closest('dialog').close();toast('Saldo inicial salvo. Agora lance seus gastos e confirme os salários quando receber.')}}finally{savingOpening=false;button.disabled=false}});
 $('#editPlan').onclick=()=>{const f=$('#planForm');f.elements.salary.value=state.plan.salary?state.plan.salary/2:'';f.elements.percent.value=state.plan.percent||10;f.elements.saved.value=state.plan.saved||'';$('#monthlyEstimate').textContent=`Salário mensal estimado: ${money(state.plan.salary||0)}`;openDialog('planDialog')};
 $('#planForm').elements.salary.addEventListener('input',e=>{$('#monthlyEstimate').textContent=`Salário mensal estimado: ${money(Number(e.target.value||0)*2)}`});
 $('#planForm').addEventListener('submit',async e=>{e.preventDefault();const f=new FormData(e.currentTarget),plan={user_id:currentUser.id,salary:(Number(f.get('salary'))||0)*2,percent:Number(f.get('percent'))||0,saved:Number(f.get('saved'))||0};if(await persist(()=>client.from('savings_plans').upsert(plan,{onConflict:'user_id'}))){e.currentTarget.closest('dialog').close();toast('Salário, contas e meta atualizados.') }});
 $('#profileButton').onclick=()=>{$('#profileForm').elements.name.value=state.name||'';openDialog('profileDialog')};$('.mobile-profile').onclick=()=>$('#profileButton').click();
 $('#profileForm').addEventListener('submit',async e=>{e.preventDefault();const name=new FormData(e.currentTarget).get('name').trim(),{error}=await client.auth.updateUser({data:{preferred_name:name}});if(error){toast('Não foi possível atualizar seu nome.');return}state.name=name;e.currentTarget.closest('dialog').close();render();toast('Seu espaço foi atualizado.')});
 document.querySelectorAll('.cancel-dialog,.dialog-close').forEach(b=>b.addEventListener('click',()=>b.closest('dialog').close()));document.querySelectorAll('dialog').forEach(d=>d.addEventListener('click',e=>{if(e.target===d)d.close()}));
 $('#prevMonth').onclick=()=>{visibleMonth.setMonth(visibleMonth.getMonth()-1);render()};$('#nextMonth').onclick=()=>{visibleMonth.setMonth(visibleMonth.getMonth()+1);render()};$('#privacyButton').onclick=()=>{hidden=!hidden;render()};$('#categoryFilter').onchange=()=>renderTransactions(state.transactions.filter(t=>t.date.slice(0,7)===monthKey(visibleMonth)));$('#viewAll').onclick=()=>{window.location.hash='lancamentos';setView('#lancamentos')};
}
async function start(){
 const config=window.APP_CONFIG||{};
 if(!config.supabaseUrl||!config.supabaseAnonKey||!window.supabase?.createClient){setupMessage('A configuração do banco ainda não foi concluída.');$('#googleLogin').disabled=true;return}
 client=window.supabase.createClient(config.supabaseUrl,config.supabaseAnonKey);bindForms();window.addEventListener('hashchange',()=>setView());setView();
 const {data:{session},error}=await client.auth.getSession();if(error){setupMessage('Não foi possível iniciar a sessão.');return}if(session)setSignedIn(session.user);else{
  try{const response=await fetch(`${config.supabaseUrl}/auth/v1/settings`,{headers:{apikey:config.supabaseAnonKey}}),settings=await response.json();if(!response.ok||!settings.external?.google){setupMessage('O projeto está conectado. Para liberar o acesso, ative o provedor Google no painel do Supabase.');$('#googleLogin').disabled=true}else setupMessage('')}
  catch{setupMessage('Não consegui verificar a configuração do projeto. Confira sua conexão com a internet.');$('#googleLogin').disabled=true}
 }
 client.auth.onAuthStateChange((_event,newSession)=>{if(newSession)setSignedIn(newSession.user);else{currentUser=null;state=emptyState();$('#authScreen').hidden=false;$('.app-shell').hidden=true}});
}
start();
