const STORAGE_KEY='meuFinanceiro.v1';
const categories={salary:{label:'Salário',icon:'↓'},home:{label:'Moradia',icon:'⌂'},food:{label:'Alimentação',icon:'◇'},transport:{label:'Transporte',icon:'↗'},health:{label:'Saúde',icon:'✚'},leisure:{label:'Lazer',icon:'✳'},other:{label:'Outros',icon:'·'}};
const money=value=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(value||0);
const dateLabel=value=>new Intl.DateTimeFormat('pt-BR',{day:'2-digit',month:'short'}).format(new Date(`${value}T12:00:00`)).replace('.','');
const todayISO=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
const monthKey=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`;
let state=loadState(),visibleMonth=new Date(new Date().getFullYear(),new Date().getMonth(),1),hidden=false;
function loadState(){try{return JSON.parse(localStorage.getItem(STORAGE_KEY))||{transactions:[],bills:[],plan:{salary:0,percent:10,saved:0},name:''}}catch{return{transactions:[],bills:[],plan:{salary:0,percent:10,saved:0},name:''}}}
function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state));render()}
function fmt(value){return hidden?'••••••':money(value)}
function render(){
 const month=monthKey(visibleMonth),items=state.transactions.filter(t=>t.date.slice(0,7)===month),income=items.filter(t=>t.type==='income').reduce((n,t)=>n+t.amount,0),expenses=items.filter(t=>t.type==='expense').reduce((n,t)=>n+t.amount,0);
 document.querySelector('#today').textContent=new Intl.DateTimeFormat('pt-BR',{weekday:'short',day:'numeric',month:'short',year:'numeric'}).format(new Date());
 document.querySelector('#monthLabel').textContent=new Intl.DateTimeFormat('pt-BR',{month:'long',year:'numeric'}).format(visibleMonth);
 document.querySelector('#balance').textContent=fmt(income-expenses);document.querySelector('#incomeTotal').textContent=fmt(income);document.querySelector('#expenseTotal').textContent=fmt(expenses);
 document.querySelector('#monthlyNote').textContent=income||expenses?(income>=expenses?'No positivo':'Atenção ao ritmo'):'Vamos começar?';
 document.querySelector('#greetingName').textContent=state.name||'você';document.querySelector('.avatar').textContent=(state.name||'M').charAt(0).toUpperCase();document.querySelector('.mobile-profile').textContent=(state.name||'M').charAt(0).toUpperCase();
 const target=(state.plan.salary||0)*(state.plan.percent||0)/100,progress=target?Math.min(100,Math.round((state.plan.saved||0)/target*100)):0;
 document.querySelector('#goalValue').textContent=fmt(target);document.querySelector('#goalDetail').textContent=state.plan.salary?`${state.plan.percent}% do seu salário de ${fmt(state.plan.salary)}`:'Defina seu salário e sua meta mensal';document.querySelector('#savedLabel').textContent=`${fmt(state.plan.saved||0)} guardados`;document.querySelector('#progressPercent').textContent=`${progress}%`;document.querySelector('#donutPercent').textContent=`${progress}%`;document.querySelector('#savingsProgress').style.width=`${progress}%`;document.querySelector('#savingsDonut').style.background=`conic-gradient(#8bce9a ${progress}%,#eef2ee ${progress}% 100%)`;
 document.querySelector('#suggestion').lastElementChild.textContent=target?(progress>=100?'Meta do mês alcançada. Que conquista!':`Faltam ${fmt(Math.max(0,target-(state.plan.saved||0)))} para a meta deste mês.`):'Um pequeno passo por mês faz diferença.';
 renderBills();renderTransactions(items);document.querySelector('#privacyButton').textContent=hidden?'⊘':'◉';
}
function renderBills(){const list=document.querySelector('#billList'),empty=document.querySelector('#emptyBills');const bills=[...state.bills].sort((a,b)=>a.dueDate.localeCompare(b.dueDate)).slice(0,3);list.innerHTML='';empty.classList.toggle('visible',!bills.length);list.hidden=!bills.length;for(const b of bills){const row=document.createElement('div');row.className='bill-item';const total=b.amount*b.remaining;row.innerHTML=`<span class="bill-icon">${esc(b.icon)}</span><span class="bill-info"><strong>${esc(b.name)}</strong><span>Vence ${dateLabel(b.dueDate)} · ${b.remaining} ${b.remaining===1?'parcela':'parcelas'} restantes</span></span><span class="bill-amount"><strong class="sensitive">${fmt(b.amount)}<small>/mês</small></strong><span class="sensitive">Faltam ${fmt(total)} no total</span></span><button class="bill-delete" aria-label="Remover fatura" title="Remover fatura">×</button>`;row.querySelector('.bill-delete').addEventListener('click',()=>{state.bills=state.bills.filter(x=>x.id!==b.id);save();toast('Fatura removida.')});list.appendChild(row)}document.querySelector('#billsFooterText').textContent=bills.length?`${state.bills.length} ${state.bills.length===1?'conta cadastrada':'contas cadastradas'} · valores totais em aberto`: 'Suas contas organizadas, sem surpresas.'}
function renderTransactions(items){const filter=document.querySelector('#categoryFilter').value;const rows=document.querySelector('#transactionRows'),empty=document.querySelector('#emptyTransactions');rows.innerHTML='';const filtered=items.filter(t=>filter==='all'||t.category===filter).sort((a,b)=>b.date.localeCompare(a.date)).slice(0,8);empty.hidden=filtered.length>0;for(const t of filtered){const cat=categories[t.category]||categories.other,tr=document.createElement('tr');tr.innerHTML=`<td>${esc(t.description)}</td><td><span class="category-cell"><span class="category-badge">${cat.icon}</span>${cat.label}</span></td><td>${dateLabel(t.date)}</td><td class="sensitive ${t.type==='income'?'value-income':'value-expense'}">${t.type==='income'?'+':'−'} ${fmt(t.amount)}</td><td><button class="row-delete" aria-label="Remover lançamento" title="Remover">×</button></td>`;tr.querySelector('.row-delete').addEventListener('click',()=>{state.transactions=state.transactions.filter(x=>x.id!==t.id);save();toast('Lançamento removido.')});rows.appendChild(tr)}}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function toast(msg){const el=document.querySelector('#toast');el.textContent=msg;el.classList.add('visible');setTimeout(()=>el.classList.remove('visible'),2300)}
function openDialog(id){document.querySelector(`#${id}`).showModal()}
document.querySelector('#addTransaction').onclick=()=>{document.querySelector('#transactionForm').reset();document.querySelector('[name="date"]').value=todayISO();openDialog('transactionDialog')};document.querySelector('#emptyAddTransaction').onclick=()=>document.querySelector('#addTransaction').click();
document.querySelector('#transactionForm').addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.currentTarget);state.transactions.push({id:crypto.randomUUID(),description:f.get('description').trim(),amount:Number(f.get('amount')),type:f.get('type'),category:f.get('category'),date:f.get('date')});e.currentTarget.closest('dialog').close();save();toast('Lançamento salvo.')});
document.querySelector('#addBill').onclick=()=>{document.querySelector('#billForm').reset();document.querySelector('[name="dueDate"]').value=todayISO();openDialog('billDialog')};document.querySelector('#emptyAddBill').onclick=()=>document.querySelector('#addBill').click();
document.querySelector('#billForm').addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.currentTarget);state.bills.push({id:crypto.randomUUID(),name:f.get('name').trim(),amount:Number(f.get('amount')),dueDate:f.get('dueDate'),remaining:Number(f.get('remaining')),icon:f.get('icon')});e.currentTarget.closest('dialog').close();save();toast('Fatura adicionada.')});
document.querySelector('#editPlan').onclick=()=>{const f=document.querySelector('#planForm');f.elements.salary.value=state.plan.salary||'';f.elements.percent.value=state.plan.percent||10;f.elements.saved.value=state.plan.saved||'';openDialog('planDialog')};document.querySelector('#planForm').addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.currentTarget);state.plan={salary:Number(f.get('salary'))||0,percent:Number(f.get('percent'))||0,saved:Number(f.get('saved'))||0};e.currentTarget.closest('dialog').close();save();toast('Meta atualizada.')});
document.querySelector('#profileButton').onclick=()=>{document.querySelector('#profileForm').elements.name.value=state.name||'';openDialog('profileDialog')};document.querySelector('.mobile-profile').onclick=()=>document.querySelector('#profileButton').click();document.querySelector('#profileForm').addEventListener('submit',e=>{e.preventDefault();state.name=new FormData(e.currentTarget).get('name').trim();e.currentTarget.closest('dialog').close();save();toast('Seu espaço foi atualizado.')});
document.querySelectorAll('.cancel-dialog,.dialog-close').forEach(b=>b.addEventListener('click',()=>b.closest('dialog').close()));document.querySelectorAll('dialog').forEach(d=>d.addEventListener('click',e=>{if(e.target===d)d.close()}));
document.querySelector('#prevMonth').onclick=()=>{visibleMonth.setMonth(visibleMonth.getMonth()-1);render()};document.querySelector('#nextMonth').onclick=()=>{visibleMonth.setMonth(visibleMonth.getMonth()+1);render()};document.querySelector('#privacyButton').onclick=()=>{hidden=!hidden;render()};document.querySelector('#categoryFilter').onchange=()=>renderTransactions(state.transactions.filter(t=>t.date.slice(0,7)===monthKey(visibleMonth)));
document.querySelector('#viewAll').onclick=()=>toast('Exibindo os lançamentos mais recentes deste mês.');render();
